import pygame
# SETTINGS

GAME_WIDTH = 900
GAME_HEIGHT = 600

SKY_SURFACE_WIDTH = GAME_WIDTH
SKY_SURFACE_HEIGHT = 600 * 0.75

GROUND_SURFACE_WIDTH = GAME_WIDTH
GROUND_SURFACE_HEIGHT = 600 * 0.25
GROUND_SURFACE_POS_Y = SKY_SURFACE_HEIGHT 

TEXT_CENTER_X = 900 / 2
SCORE_POS_Y = 600 * 0.125




