import pygame
# SETTINGS

# Game
GAME_WIDTH = 900
GAME_HEIGHT = 600

# Statics
SKY_SURFACE_WIDTH = GAME_WIDTH
SKY_SURFACE_HEIGHT = 600 * 0.75

GROUND_SURFACE_WIDTH = GAME_WIDTH
GROUND_SURFACE_HEIGHT = 600 * 0.25
GROUND_SURFACE_POS_Y = SKY_SURFACE_HEIGHT 

# Text
TEXT_CENTER_X = GAME_WIDTH / 2
SCORE_POS_Y = GAME_HEIGHT * 0.125
SCORE_COLOR = (64, 64, 64)
TEXT_COLOR = (111, 196, 169)

TITLE_POS_Y = (GAME_HEIGHT / 3.5) 
GAME_MSG_POS_Y = GAME_HEIGHT - TITLE_POS_Y 




